# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VovSoft.RichTextEditor
PackageVersion: 1.2.0.0
InstallerLocale: en-US
ReleaseDate: 2026-09-27
Installers:
- Architecture: x86
  InstallerType: inno
  Scope: user
  InstallerUrl: https://files.vovsoft.com/rich-text-editor.exe
  InstallerSha256: 9F3395CA73565EE5DC3B482626FC9AC426A7F9158535AE319C2E4BB2F620A9AB
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  InstallerSwitches:
    Custom: /CURRENTUSER
  ProductCode: Rich Text Editor_is1
  AppsAndFeaturesEntries:
  - ProductCode: Rich Text Editor_is1
  ElevationRequirement: elevatesSelf
- Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://files.vovsoft.com/rich-text-editor.exe
  InstallerSha256: 9F3395CA73565EE5DC3B482626FC9AC426A7F9158535AE319C2E4BB2F620A9AB
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  InstallerSwitches:
    Custom: /ALLUSERS
  ProductCode: Rich Text Editor_is1
  AppsAndFeaturesEntries:
  - ProductCode: Rich Text Editor_is1
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\VOVSOFT\Rich Text Editor'
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: rteditor.exe
    PortableCommandAlias: rteditor
  InstallerUrl: https://files.vovsoft.com/rich-text-editor-portable.zip
  InstallerSha256: D0A932FAEA98F33E370AFAB02393AA30408859A21E8D1985988AF8DE927B618A
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
