# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VovSoft.MergeAudioFiles
PackageVersion: 1.3.0.0
InstallerLocale: en-US
ReleaseDate: 2026-10-04
Installers:
- Architecture: x86
  InstallerType: inno
  Scope: user
  InstallerUrl: https://files.vovsoft.com/merge-audio-files.exe
  InstallerSha256: 9A658CD4EA1E96D736F036FAA9044C7B9E7DA6433FFFB4E2B56E627B2A270110
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  InstallerSwitches:
    Custom: /CURRENTUSER
  ProductCode: Merge Audio Files_is1
  AppsAndFeaturesEntries:
  - ProductCode: Merge Audio Files_is1
  ElevationRequirement: elevatesSelf
- Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://files.vovsoft.com/merge-audio-files.exe
  InstallerSha256: 9A658CD4EA1E96D736F036FAA9044C7B9E7DA6433FFFB4E2B56E627B2A270110
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  InstallerSwitches:
    Custom: /ALLUSERS
  ProductCode: Merge Audio Files_is1
  AppsAndFeaturesEntries:
  - ProductCode: Merge Audio Files_is1
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\VOVSOFT\Merge Audio Files'
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: mergeaudio.exe
    PortableCommandAlias: mergeaudio
  InstallerUrl: https://files.vovsoft.com/merge-audio-files-portable.zip
  InstallerSha256: A5CF998731BCDDBC9253699483B624BE24EAE1CBCB237B9AC7FF7D991C0EA12C
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
